  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres_password
      context: ./nginx
    ports:
      - "3050:80"
