version: "3"
services:
  postgres:
    image: "postgres:latest"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis:latest"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /mnt/c/Users/Mostafa/Desktop/DevSpace/docker_space/multi-container/app/node_modules
      - /mnt/c/Users/Mostafa/Desktop/DevSpace/docker_space/multi-container/server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /mnt/c/Users/Mostafa/Desktop/DevSpace/docker_space/multi-container/app/node_modules
      - /mnt/c/Users/Mostafa/Desktop/DevSpace/docker_space/multi-container/client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /mnt/c/Users/Mostafa/Desktop/DevSpace/docker_space/multi-container/app/node_modules
      - /mnt/c/Users/Mostafa/Desktop/DevSpace/docker_space/multi-container/worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
